Removal of redundant updating of gameplay variables
diasurgical/devilutionX pull request #1395
Opened 2021-04-06 23:37 UTC by FluffyQuack

When you click on singleplayer in the main menu, this function gets called: `mainmenu_single_player()`

That loads several gameplay variables from the config.

However, as you progress through the character selection menus and before going ingame, this function gets called: `NetInit`

That loads the same gameplay variables from the config. I should note that this function gets called even in singleplayer (when I first saw its name, I was thinking it was run only in network mode), which makes the actions in `mainmenu_single_player()` unnecessary.

In order to remove redundant code (and to make it less confusing as to when important variables are actually initialized), I think it would be a good change to remove these lines from `mainmenu_single_player()`

2021-04-07 03:08 UTC, julealgon requested changes
Can't we just get rid of these variables altogether? All of them are used in very few places, so I actually see no reason for them to exist in the first place: just read them from the options directly where it's needed.

2021-04-07 05:32 UTC, AJenbo commented
they are there so that in multiplayer you will agree on a game mode without changing your config

2021-04-09 09:55 UTC, merged

2021-04-10 02:45 UTC, julealgon commented
> they are there so that in multiplayer you will agree on a game mode without changing your config

Makes sense. Ultimately, I think we need a settings override mechanism so that settings can be set based on a hierarchy, so that multiplayer broadcast settings override local settings seamlessly.

I really dislike the current hardcoded variables there but I understand this will take a while to create. I have no idea if there is a C++ settings library that would allow such a thing, something similar to [Microsoft.Extensions.Options](https://www.nuget.org/packages/Microsoft.Extensions.Options/)

2021-04-10 02:54 UTC, AJenbo commented
We could replace the globals with `sgGameInitInfo` with out issue.

2021-04-10 03:27 UTC, AJenbo commented
@julealgon see if you like this https://github.com/diasurgical/devilutionX/pull/1450/files