Check _pmode for player death when skipping hit recovery.
diasurgical/devilutionX pull request #1509
Opened 2021-04-13 06:15 UTC by StephenCWills

This resolves #1353

Based on my testing, this bug does not affect PvP.

I edited a character's stats to make testing easier. Here is a save file.
[single_0.sv.zip](https://github.com/diasurgical/devilutionX/files/6301584/single_0.sv.zip)

Missles can be tested against skeleton archers on dlvl 2. Head NW to reach the stairs.

2021-04-13 09:57 UTC, AJenbo commented
Looking just at the diff im still not sure why tjis was happening, could you give a summery of what the cause of the error was?

2021-04-13 14:13 UTC, NiteKat commented
Looking at the diff and from what I know about the bug, it's because you lose life first with mana shield, and then mana shield refunds the life and removes mana. So if you have 5 life say, and get hit, you'll take 5 life of damage... now your life is at 0, so SyncPlrKill will be called, and StartPlrHit will NEVER be called. StartPlrHit is where the stun check is. In the end your character doesn't die though, because mana shield refunds the life back.

2021-04-13 14:26 UTC, StephenCWills commented
@NiteKat is correct. If you look at `SyncPlrKill()`, it actually checks all the missles to find a mana shield that might prevent the player's death and, if so, skips calling `StartPlayerKill()`.
https://github.com/diasurgical/devilutionX/blob/master/Source/player.cpp#L2006

If the player does happen to die in spite of the mana shield, the `MI_ManaShield()` should call `SyncPlrKill()` again after marking the mana shield for deletion. But the `MI_ManaShield()` function doesn't actually know how much damage the player received from any individual attack or whether the attack had knockback. So calling `StartPlrHit()` or handling knockback at that time isn't possible. I simply added an additional check to determine whether `StartPlayerKill()` was actually invoked before skipping `StartPlrHit()` logic.

2021-04-13 14:35 UTC, StephenCWills commented
Also potentially worth noting, this does have the effect of putting the player into the hit-recovery animation and playing the sound effect in the same frame as the player's death animation and sound effect. This does not normally happen when the player is not using Mana Shield, where the player will instantly transition to the death animation without ever entering the hit-recovery state. I considered attempting a more complex solution to fix the inconsistency, but I ultimately decided against it because it actually is consistent with how the player transitions to the death state in the PvP logic. I feel it's more likely that the behavior when not using Mana Shield is simply the result of an optimization to skip unnecessary animation state changes.

2021-04-13 14:44 UTC, NiteKat commented
I remember reading this bug got introduced by Blizz during a patch, so I think they saw the hit stun and death starting on the same frame being a "bug" and this is how they fixed it, but ended up introducing the bug of never getting hit stunned with mana shield and low life. I don't have a reference off hand for that info.

2021-04-13 16:32 UTC, StephenCWills commented
I haven't been able to find any indication on whether or when this was introduced by reviewing patch notes, Jarulf's Guide, or Google searches. On the contrary, I found at least one source that claims the bug has been around as long as Diablo 1, though it's just hearsay on a forum. There were a bunch of fixes for Mana Shield in 1.07, but nothing that stood out to me as being relevant to this bug.

Perhaps it's also worth noting that my findings in terms of the cause of this bug are not consistent with the description in Jarulf's Guide. Jarulf's Guide indicates that the Mana Shield logic puts the player back in standing mode if they were previously in dying mode, but as far as I could tell, the player never enters dying mode in the first place. I playtested this change with the attached savegame so I'm confident this change fixes the issue.

2021-04-14 03:08 UTC, NiteKat commented
I noticed the same thing when looking at the official patch notes. 1.07 had a lot of Mana Shield changes, but couldn't find diddly squat on this particular issue. 😆

2021-04-14 10:12 UTC, AJenbo commented
Wouldn't a better fix to check for a mana shield at the time of getting hit and not ever subtracting any health?

2021-04-14 12:49 UTC, StephenCWills commented
Good point. That was my first thought when I started, but I got a little intimidated when I discovered that there is no reference from the player to the existence of the Mana Shield. Having said that, `SyncPlayerKill()` already has the code to search for the Mana Shield missile associated with the player so it shouldn't be too bad. I can certainly give it a shot.

2021-04-18 04:35 UTC, StephenCWills commented
I just pushed a new commit based on comments from @AJenbo. This new version was tested against the save file attached to this pull request and also with Blood Star, Bone Spirit, and Constricting Ring. Here are some additional behavioral changes as compared to the game's original logic.

* If the player receives damage from two sources in the same frame, the 33% reduction applies to each amount individually. This can produce slightly different results due to truncation errors.
* If the player receives healing in the same frame as they receive damage, the original code would have applied both to HP, causing some or all of that damage to bypass Mana Shield. This code will apply the damage to Mana Shield and the healing to HP separately.
* If the player takes damage that exceeds their current Mana, only the damage that applies to Mana is subject to the 33% reduction. The rest of the damage is readjusted to the original amount before being applied to HP.
* The player will no longer take damage through Mana Shield when Infravision wears off or during transitions of the Rage skill.

As a bit of a side-effect, this now also resolves #1111.

2021-04-18 08:44 UTC, qndel approved these changes
![tenor (3)](https://user-images.githubusercontent.com/14297035/115139591-ff7b1f00-a032-11eb-8f59-f1b2e1b50390.gif)

2021-04-18 14:33 UTC, StephenCWills commented
Having slept on it, I realize now that I forgot to remove the code at the end of `CalcPlrItemVals()` that keeps the missile variables up to date.

@qndel I see this has already been approved, but do you mind if I add a little cleanup commit to this pull request?

2021-04-18 14:44 UTC, qndel commented
> Having slept on it, I realize now that I forgot to remove the code at the end of `CalcPlrItemVals()` that keeps the missile variables up to date.
> 
> @qndel I see this has already been approved, but do you mind if I add a little cleanup commit to this pull request?

Go on :D

2021-04-18 14:56 UTC, StephenCWills commented
Done

2021-04-18 15:37 UTC, qndel approved these changes
Looks good!

2021-04-18 16:08 UTC, qndel requested changes

2021-04-18 19:11 UTC, AJenbo approved these changes

2021-04-18 19:12 UTC, merged