Update pt_BR.po
diasurgical/devilutionX pull request #1786
Opened 2021-04-30 22:57 UTC by altiereslima

2021-05-01 00:39 UTC, AJenbo commented
Good to see you continue this :)

With 86% this is now the most complete translation.

2021-05-01 20:23 UTC, julealgon commented
Will review once conflicts are solved.

2021-05-01 20:26 UTC, AJenbo commented
Done

2021-05-01 22:34 UTC, AJenbo commented
Cancled CI builds as this is just a text file and the server is overloaded atm.

2021-05-01 22:46 UTC, julealgon requested changes
The boss names seem completely nonsensical and cringey in pt-BR. There is no equivalent thing in Portuguese to the 2 word combinations so common in English. There seems to have been a crazy effort here though in making something out of it, so I appreciate that.

No specific suggestion from me besides just not playing in Portuguese though :D

2021-05-01 22:46 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Homicida"
This also looks poor. I think we need a more general term here:
```suggestion
msgstr "Matador"
```

2021-05-01 22:46 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Desfiador"
Tense looks completely wrong on this one:
```suggestion
msgstr "O Retalhado"
```

2021-05-01 22:46 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Cria do Inferno"
We already used "Cria" for "Kin" . I think we should consider using different words for these to differentiate.
```suggestion
msgstr "Prole do Inferno"
```

2021-05-01 22:46 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "O Senhor Sombrio"
I think this would be more in tone:
```suggestion
msgstr "O Senhor das Trevas"
```

2021-05-01 22:46 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Arqui-Litch"
```suggestion
msgstr "Arqui-Lich"
```

2021-05-01 22:46 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Kaikatarro"
Where did this come from?

2021-05-01 22:46 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Vex Vermelho"
The literal meaning of "Vex" makes some sense for her name I think? Also, should be feminine:
```suggestion
msgstr "Aflição Vermelha"
```

2021-05-01 22:46 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Osteocéfalo Machado"
I have no idea how to translate this one but this seems wrong.

2021-05-01 22:46 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Vomirrato, o Impuro"
I'd use "imundo" here:
```suggestion
msgstr "Vomirrato, o Imundo"
```

2021-05-01 22:46 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Víbice Negro, o Flamejante"
I'm curious where this came from. The translation makes zero sense to me. Isn't the "ash" in the original related to actual ash?
```suggestion
msgstr "Cinzas Negras, o Flamejante"
```

2021-05-01 22:47 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Kaikatarro"
I guess the same could be asked of all boss names... just ignore this.

2021-05-01 22:50 UTC, AJenbo commented on Translations/pt_BR.po
> +msgstr "Menu"
It doesn't but it makes it much easier to see that the translation is complete. It's especially helpful for someone who doesn't speak the language as I can see if the translation needs to be updated and contact the maintainer. Same if we integrate with some system that lists the current state of various translations:
![image](https://user-images.githubusercontent.com/204594/116796895-693e0300-aae0-11eb-9a99-11f56d5a0bfb.png)

2021-05-11 00:37 UTC, julealgon requested changes
Ok I started reviewing again but I don't understand why comments were marked as resolved but not fixed and not replied to.

I'll refrain from reviewing until this is ready.

2021-05-11 00:37 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Invent."
Why was this marked as resolved?

2021-05-11 00:37 UTC, julealgon commented on Translations/pt_BR.po
> +msgstr "Ativar relatório detalhado"
Why mark as resolved?

2021-05-16 21:09 UTC, julealgon commented
@AJenbo , I'm seeing a few translation-related changes being done recently. If we keep this PR open for too long, we'll be risking conflicts and extra delays, right?

If so, consider just merging this and we call go over the entire translation again later. It looks like the author is not very responsive here to allow for incremental updates.

2021-05-16 21:36 UTC, merged

2021-07-29 03:56 UTC, AJenbo commented
Hey @altiereslima do you have time to work on the remaning 17% of the translation? I have updated the translation file to match the latest content:

https://github.com/diasurgical/devilutionX/blob/master/Translations/pt_BR.po
Note that some of the strings are located in the Android XML files:
https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values-pt-rBR/strings.xml
Template:
https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values/strings.xml

2021-07-29 13:48 UTC, julealgon commented
I have since discovered that there is a pt-BR fan translation for the PSX version of Diablo. I'm not sure but I'd assume some/most/(all?) of these translations came from that project.

Just wanted to throw this here for future reference.

2021-08-02 01:41 UTC, altiereslima commented
Credits: Victor Maristane https://github.com/maristane
[devilutionX(pt-BR).zip](https://github.com/diasurgical/devilutionX/files/6913870/devilutionX.pt-BR.zip)

2021-08-08 01:16 UTC, AJenbo commented
![image](https://user-images.githubusercontent.com/204594/128617664-c06e71f3-50c0-4552-8094-10be3f74b4bb.png)