RU translation, part 3
diasurgical/devilutionX pull request #1956
Opened 2021-05-13 16:15 UTC by AAS

Some fixes, more "е"->"ё" changes.
It's probably the last one until the game start showing intl. symbols instead of question marks.

In other news, there is good RU translation: https://opennota2.duckdns.org/book/78016/455179?Orig_page=1 
But there is no gettext infrastructure, just eng+rus quest texts side by side.

2021-05-13 18:35 UTC, AJenbo commented
Let's see if @Iniquitatis wants to review this before it's merged :)

2021-05-13 20:02 UTC, Iniquitatis requested changes

2021-05-13 20:02 UTC, Iniquitatis commented on Translations/ru.po
> +"Я - обязанная за все самой себе корова. Стань кем-нибудь и... тогда мы "
```suggestion
"Я - обязанная за всё самой себе корова. Стань кем-нибудь и... тогда мы "
```

2021-05-13 21:08 UTC, AAS commented on Translations/ru.po
> +msgstr "Свиток Портала в Город"
Я не вижу в этом проблемы. Скорее нужен свод правил, что делать, а что не делать, тогда это уже будет более очевидно другим переводчикам, возможно правила должны распространяться на все языки.

2021-05-13 21:29 UTC, glebm commented on Translations/ru.po
> +msgstr "Магия"
A trailing space is needed here and for Fire/Lightning

2021-05-15 10:18 UTC, glebm approved these changes

2021-05-15 10:49 UTC, AJenbo commented
@glebm wait you speak Russian as well?

2021-05-15 10:50 UTC, merged