Leverage 'Point' struct on monster functions
diasurgical/devilutionX pull request #2056
Opened 2021-05-25 03:10 UTC by julealgon

This PR leverages the `Point` struct on all exposed functions in `monster.h`

2021-05-25 16:49 UTC, AJenbo commented on Source/monster.cpp
> +		while (!done && (startPoint.x != endPoint.x || startPoint.y != endPoint.y)) {
```suggestion
		while (!done && (startPoint != endPoint)) {
```

2021-05-25 16:52 UTC, AJenbo commented on Source/monster.cpp
> +			endPoint.x = tmp;
Could we use `std::swap()` instead of `int tmp`, or at least `Point tmp`?

2021-05-25 16:52 UTC, AJenbo commented on Source/monster.cpp
> +			endPoint.y = tmp;
Same as 4806

2021-05-25 16:52 UTC, AJenbo commented on Source/monster.cpp
> +		while (!done && (startPoint.y != endPoint.y || startPoint.x != endPoint.x)) {
```suggestion
		while (!done && (startPoint != endPoint)) {

```

2021-05-25 16:55 UTC, AJenbo commented on Source/monster.cpp
> +	yorg = startPoint.y;
A few things in this function could benefit from xorg/yorg becomming `Point originalStart`.

2021-05-25 17:01 UTC, AJenbo commented on Source/monster.cpp
> +	yorg = startPoint.y;
`startPoint` might also be better named as just point or position as it seams to be changed over time. Then xorg/yorg could instead be called `startPoint`.

2021-05-25 17:06 UTC, AJenbo requested changes
Looks like this moves a chunk of functions in to the 2 or less parameter range :+1: 

The naming `LineClear` of `x1`/`y1` in as `startingPoint` seams be be a bit misleading. Swapping of start and end point is still done as if they where individual values, as well as comparisons to check if the position advanced.

2021-05-25 17:09 UTC, AJenbo commented on Source/monster.cpp
> +			done = ((startPoint.y != yorg || startPoint.x != xorg) && !Clear(entity, startPoint));
If xorg/yorg was also redefined this could be reduced to:
```suggestion
			done = (startPoint != origin && !Clear(entity, startPoint));
```

2021-05-25 17:11 UTC, AJenbo commented on Source/monster.cpp
> +			done = ((startPoint.x != xorg || startPoint.y != yorg) && !Clear(entity, startPoint));
Would look nicer as:
```suggestion
			done = startPoint != origin && !Clear(entity, startPoint);
```

2021-05-25 17:41 UTC, julealgon commented
> The naming LineClear of x1/y1 in as startingPoint seams be be a bit misleading. Swapping of start and end point is still done as if they where individual values, as well as comparisons to check if the position advanced.

Do you have any suggestions? I don't know what these methods do, so sometimes naming the arguments can be tricky. Should I just make them `firstPosition` and `secondPosition` instead then, or something even more specific?

2021-05-25 18:49 UTC, AJenbo commented
> > The naming LineClear of x1/y1 in as startingPoint seams be be a bit misleading. Swapping of start and end point is still done as if they where individual values, as well as comparisons to check if the position advanced.
> 
> Do you have any suggestions? I don't know what these methods do, so sometimes naming the arguments can be tricky. Should I just make them `firstPosition` and `secondPosition` instead then, or something even more specific?

Please se this comment: https://github.com/diasurgical/devilutionX/pull/2056#discussion_r638992894

2021-05-28 18:47 UTC, AJenbo commented
Merged manually via https://github.com/diasurgical/devilutionX/commit/4668a526ebb7a4f596551601474a8e8b4d76ee92

2021-05-28 18:47 UTC, closed without merging

2021-05-28 19:43 UTC, julealgon commented
> Merged manually via 4668a52

Sorry for the delay in fixing the issues. I was going to do that starting today. Thanks for merging the changes.

2021-05-28 19:50 UTC, AJenbo commented
No worries, have a follow up I wanted to apply so went ahead, glad you didn't mind :)

2021-05-28 20:21 UTC, AJenbo commented
here you go https://github.com/diasurgical/devilutionX/pull/2079