♻️Simplify loops in to mulitplications
diasurgical/devilutionX pull request #2225
Opened 2021-06-24 18:15 UTC by AJenbo

2021-06-24 18:44 UTC, StephenCWills commented on Source/missiles.cpp
> +		*mind += myPlayer._pLevel;
Instead of initializing to zero and adding, should we just set the value?

2021-06-24 18:53 UTC, StephenCWills requested changes
I suppose it doesn't just apply to Apocalypse. We can consider consolidating all of these to look more like a damage calculation formula. Honestly, I don't have a particular preference so use your judgment. However, I do think there's no sense initializing to zero and then using `+=`.

2021-06-24 23:59 UTC, AJenbo commented
> consider consolidating all of these to look more like a damage calculation formula

Gave all the calculations and overhaul, hope it's to your liking :)

2021-06-25 00:57 UTC, StephenCWills commented on Source/missiles.cpp
> +		*maxd += AddClassHealingBonus((4 * myPlayer._pLevel) + (6 * sl) + 10, myPlayer._pClass) - 1;
```suggestion
		*mind = AddClassHealingBonus(myPlayer._pLevel + sl + 1, myPlayer._pClass) - 1;
		*maxd = AddClassHealingBonus((4 * myPlayer._pLevel) + (6 * sl) + 10, myPlayer._pClass) - 1;
```

2021-06-25 01:20 UTC, StephenCWills approved these changes
Fantastic work! It looks great. 😄

2021-06-25 01:57 UTC, merged

2021-06-26 23:06 UTC, julealgon commented on Source/missiles.cpp
> +}
This method would be vastly more readable with a switch IMHO.

2021-06-26 23:06 UTC, julealgon commented on Source/missiles.cpp
> +		return hp + hp / 2;
I'd suggest using `hp * 1.5` here so that all statements look similar.