new transleta
diasurgical/devilutionX pull request #2242
Opened 2021-06-26 22:59 UTC by ybrbnf2080

2021-06-26 23:03 UTC, ybrbnf2080 commented
sorry, I forgot how to use the git)) and also, apparently we are using different versions of the program, and therefore my formatting has changed a little

2021-06-26 23:27 UTC, julealgon commented
Please write specific PR titles. "new translation" is extremely broad and generic.

2021-06-27 18:55 UTC, ALJAALEID approved these changes

2021-06-27 19:10 UTC, AJenbo commented
@Iniquitatis or @AAS would one of you be willing to review this?

2021-06-27 20:31 UTC, Iniquitatis commented
@AJenbo Sure, I'll do it tomorrow.

2021-06-27 21:25 UTC, tsunamistate reviewed
Did an incomplete review before going to bed, pointed out the most obvious mistakes I found
A lot of changes in the file are just moving existing text for some reason, like margins were expanded. Is this OK?

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Гидра"
"Гидры"
Надо слонить слово

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Змеевой"
Тут тоже другое слово нужно

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Утиный"
Причём тут утка к драконам?
Нужен синоним

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "качество"
Начиная отсюда до Source/itemdat.cpp:287, насколько я понял должны быть качественные приставки
Все слова тут надо склонять

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "увеличить"
Это идёт от to maim - калечить

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "параличь"
"паралич" без мягкого знака

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "виликолепный"
"великолепный"

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "коррупция"
"Порча" больше подойдёт

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "личь"
"пиявка"

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "пирсинг"
Сомневаюсь что тут именно это имеется в виду
Отсюда до Source/itemdat.cpp:371 идут приставки к типу пробивания брони(?)
Так что:
1) Склонение слов
2) Здесь должно быть "пронизывающий" или "пронзительный"

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Тесак мясника"
"Тесак Мясника"
Мясник довольно важный персонаж, так что его с большой буквы пишем

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Лук смерти"
"Лук мертвецов" может быть?

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Манглер"
Не подходит слово, но лучше варианта пока не придумал

2021-06-27 21:25 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Глеамсонг"
Нужно найти вариант получше

2021-06-27 21:47 UTC, AJenbo commented
> A lot of changes in the file are just moving existing text for some reason, like margins were expanded. Is this OK?

@ybrbnf2080 mentions this, the reason is that a much older version of Poedit was used which apparently calculates the text width differently. It doesn't affect the end result but it makes for more diff and a harder time reviewing things. I might be able to update the file to reduce the diff, but ideally @ybrbnf2080 should update Poedit so that this doesn't happen.

2021-06-27 23:28 UTC, glebm commented on Translations/ru.po
> +msgstr "Манглер"
Можно например "Увечитель" или "Калечитель", но тоже странновато

2021-06-27 23:31 UTC, glebm commented on Translations/ru.po
> +msgstr "Глеамсонг"
Например, "Блестящий Звук"
Не совсем дословно, но учитывает что посох даёт 76 Phasing Charges

2021-06-28 02:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Умения"
"Spells" is not "Skills". 
Нужно заклинания/чары/магия.

2021-06-28 02:57 UTC, AAS commented on Translations/ru.po
> +msgstr "Короткий мечь"
Ь

2021-06-28 02:58 UTC, AAS commented on Translations/ru.po
> +msgstr "Клуб"
Дубина

2021-06-28 02:59 UTC, AAS commented on Translations/ru.po
> +msgstr "Короткое посох маны"
КороткИЙ

2021-06-28 03:00 UTC, AAS commented on Translations/ru.po
> +msgstr "Крест Арклейна"
Какой крест? Какого Арклейна?
Лучше вернуть как было.

2021-06-28 03:03 UTC, AAS commented on Translations/ru.po
> +msgstr "Лезвие Грисуолда"
Нужно вернуть **везде** Гризвольда на место, это наиболее частый перевод в рунете.
Это всё равно, что писать доктор Уотсон вместо Ватсона.

2021-06-28 03:06 UTC, AAS commented on Translations/ru.po
> +msgstr "Хороший шлем"
Великий/большой шлем.
Описывается размер, а не качество.

2021-06-28 03:07 UTC, AAS commented on Translations/ru.po
> +msgstr "Тяжёлая кожаная броня"
Hard != Heavy

2021-06-28 03:11 UTC, AAS commented on Translations/ru.po
> +msgstr "Кожаный Доспех с заклёпками"
Доспех с большой, тогда как в остальных строках только первое слово в капсе.

2021-06-28 03:11 UTC, AAS commented on Translations/ru.po
> +msgstr "Кольцо кольчуги"
Это не кольцо.

2021-06-28 03:12 UTC, AAS commented on Translations/ru.po
> +msgstr "Пластина"
Доспех

2021-06-28 03:12 UTC, AAS commented on Translations/ru.po
> +msgstr "Готическая пластина"
Доспех.

2021-06-28 03:12 UTC, AAS commented on Translations/ru.po
> +msgstr "Небольшой щит"
Маленький

2021-06-28 03:16 UTC, glebm commented on Translations/ru.po
> +msgstr "Тяжёлая кожаная броня"
Suggestion: Дублёная кожаная броня

2021-06-28 03:17 UTC, AAS commented on Translations/ru.po
> +msgstr "Воздушный щит"
Он как минимум треугольный, но никак не воздушный.
https://www.google.com/search?q=%D1%82%D1%80%D0%B5%D1%83%D0%B3%D0%BE%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9+%D1%89%D0%B8%D1%82

2021-06-28 03:17 UTC, AAS commented on Translations/ru.po
> +msgstr "Городской щит"
Башенный

2021-06-28 03:17 UTC, AAS commented on Translations/ru.po
> +msgstr "Смазка точности"
Масло

2021-06-28 03:17 UTC, AAS commented on Translations/ru.po
> +msgstr "Смазка резкости"
Масло

2021-06-28 03:18 UTC, glebm commented on Translations/ru.po
> +msgstr "Воздушный щит"
Каплевидный или миндалевидный щит https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%BF%D0%BB%D0%B5%D0%B2%D0%B8%D0%B4%D0%BD%D1%8B%D0%B9_%D1%89%D0%B8%D1%82

2021-06-28 03:18 UTC, AAS commented on Translations/ru.po
> +msgstr "Смазка"
Масло

2021-06-28 03:18 UTC, AAS commented on Translations/ru.po
> +msgstr "Свиток освещения"
Молнии

2021-06-28 03:18 UTC, AAS commented on Translations/ru.po
> +msgstr "Свиток Огненного шара"
Wall != Ball

2021-06-28 03:21 UTC, glebm commented on Translations/ru.po
> +msgstr "урон: {:d}  Продолжительность: {:d}/{:d}"
Прочность

2021-06-28 03:22 UTC, glebm commented on Translations/ru.po
> +msgstr "броня:{:d}  Несокрушимая"
```suggestion
msgstr "броня: {:d}  Несокрушимая"
```

2021-06-28 15:46 UTC, Iniquitatis requested changes

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Короткий посох заряженной стрелы"
Не уверен, что "стрела" здесь уместна (см. thunderbolt).

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Метиорит"
```suggestion
msgstr "Метеоритный"
```
Meteor**ic** же.

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Таинственный"
```suggestion
msgstr "Причудливый"
```
Понимаю, что strange и weird — синонимы, но так, вероятно, будет несколько точнее.

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Дефектный"
"Порочный" или "беспощадный". Маловероятно, что этот префикс говорит о дефектности предмета.

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Военный"
```suggestion
msgstr "Воинский"
```
Скорее, так. Принадлежит воину.

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Лорда"
```suggestion
msgstr "Лордский"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Гиена"
```suggestion
msgstr "Гиений"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Арханагельский"
```suggestion
msgstr "Архангельский"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Светящийся"
Lighting — освещение.
Light**n**ing — молния.
Здесь второе.

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Двойникское"
```suggestion
msgstr "Двойникский"
```
Почему здесь прилагательное среднего рода, когда в остальных случаях используется мужской род?

(К слову, я вообще не уверен, что в русском языке присутствует такое понятие.)

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "слезы"
```suggestion
msgstr "слёзы"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "хрупкий"
```suggestion
msgstr "хрупкость"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "умения"
```suggestion
msgstr "умение"
```
Единственное число.

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "меткий"
```suggestion
msgstr "меткость"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "точный"
```suggestion
msgstr "точность"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "совершенный"
```suggestion
msgstr "совершенство"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "виликолепный"
```suggestion
msgstr "великолепие"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "титанизм"
```suggestion
msgstr "титаны"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "гигантизм"
```suggestion
msgstr "гиганты"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "зодиака"
```suggestion
msgstr "зодиак"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "лиса(шики)"
```suggestion
msgstr "лиса"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "орел"
```suggestion
msgstr "орёл"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "хлипкий"
```suggestion
msgstr "хлипкость"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "хрупкий"
```suggestion
msgstr "хрупкость"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "состав"
```suggestion
msgstr "структура"
```
Вероятнее всего.

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "тьма(ямии)"
```suggestion
msgstr "тьма"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "деньги"
```suggestion
msgstr "много"
```
"Many" != "Money".

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "разлогатся"
```suggestion
msgstr "разлагаться"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Лук Разлома"
```suggestion
msgstr "Лук разлома"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Орлиный крик"
```suggestion
msgstr "Орлиный рог"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Черная бритва"
```suggestion
msgstr "Чёрная бритва"
```

2021-06-28 15:46 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Преисподня"
```suggestion
msgstr "Преисподняя"
```

2021-06-28 15:54 UTC, Iniquitatis commented
Couldn't review more, there are too many changes for my browser to handle.
It would be much easier to review this PR if it was separated in multiple commits or even PRs.

Still, there's quite a few typos and grammatical errors. Not sure if I can recommend this PR to be merged.

2021-06-28 15:56 UTC, AAS requested changes

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Свиток Фаербола"
Огненного шара.

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Свиток защиты"
Стража

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Свиток вспышки"
Уже используется в scroll of flash.

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Молотило"
Цеп

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Метиорит"
Метеоритный

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Дефектный"
Злобный

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Заточеный"
Острый

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Малиновый"
Багровый

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "убийство"
Здесь и далее идут суффиксы, на сколько я знаю.
Всё нужно склонять "убийство" -> "убийства" и так далее.

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Початок {:s}"
Ухо {:s}

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Стойка с оружием"
На русском это значит "... увеличивает <что-то>  оружия ..."

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr[1] "заклинания повышены на {:d} уровеня"
уровня

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr[1] "заклинания понижены на {:d} уровеня"
урвоня

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Дополнительные сборы"
Это про магию, имеется в виду заряды.

2021-06-28 15:56 UTC, AAS commented on Translations/ru.po
> +msgstr "Продолжительность: {:d}/{:d},  "
Прочность

2021-06-28 16:04 UTC, AAS commented
@AJenbo It's very controversial commit, to put it mildly. I'm against it if you ask me.

2021-06-28 17:21 UTC, glebm commented on Translations/ru.po
> +msgstr "Кольцо кольчуги"
И не кольчуга. Ring Mail это когда на кожаную броню нашивают металлические кольца.
Кольчуга - это броня сплетённая и металлических колец.

https://en.wikipedia.org/wiki/Ring_armour

2021-06-29 01:24 UTC, M1sh2 commented
https://www.old-games.ru/wiki/Diablo_(%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D1%8B)
По поводу переводов , может стоит взять за основу пиратский русификатор команды stream ? Я вижу что много текста было изменено, не в лучшую сторону

2021-06-29 07:21 UTC, M1sh2 commented on Translations/ru.po
> +msgstr "Кольцо кольчуги"
Кольцевая броня (https://tactilehobby.com/chain-mail-vs-ring-mail/, https://ru.xcv.wiki/wiki/Ring_armour)
обозначить как то , не просто "кольчуга", я думаю не получится.

2021-07-29 00:33 UTC, AJenbo commented
Based on the reviews I have opted to only merge the new translations from this PR: https://github.com/diasurgical/devilutionX/commit/4dbaca06e2c06f95ff7843f7e32e3e41eaf9c80f

This brings the Russian translation to 68% but it is probably in need of prof reading.

2021-07-29 00:33 UTC, closed without merging

2021-07-29 15:40 UTC, AAS commented
Things like "мечь", "Кольцо кольчуги", "заклинания повышены на {:d} уровеня", "Банка", "деньги" ("translated" from word "many" instead of "money") and so forth are not acceptable at all.

Imagine your hero finds something and identifies it as "Canned cword of duration". Yay!

Merging things like that brings more pain when you trying to proofread and fix it.

2021-07-29 16:32 UTC, AJenbo commented
Hmm I was not aware that it was that off track, I can revert the merge. But I'm not sure if it will help much as I don't know about the rest of the translation and not much else seams to be happening with this translation.

Any recommendations?

2021-07-29 16:53 UTC, AAS commented
I think translation's low activity mainly caused by the fact that all non-latin chars are displayed as "?".
You can't see result of you work, adapt to in-game interface bounds, revise it if it looks odd in the larger strings like "<suffix> <thing> of <prefix>".
Those things poisoned my enthusiasm after a while.

2021-07-30 04:13 UTC, SourceCodeDeleted commented
The translations need help. I started this on my phone and haven't had the time to upload it )

If you are in the discord we can discuss this.  Someone mentioned using LUA because we need something to notice when the object is female.