Russian translation
diasurgical/devilutionX pull request #2478
Opened 2021-07-31 14:09 UTC by AAS

Almost 100% translation (except 5 quirks that come from source files/.pot).

Please, to keep the review as simple as possible, suggest only grammatical and mistranslation fixes.

Keep your upper/lower chars changes to other PRs.

2021-07-31 14:40 UTC, AJenbo commented
ha ha, you just blew my mind :D

2021-07-31 14:42 UTC, AJenbo commented
Would you be willing to also translate the 10 lines for the Android app?

https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values/strings.xml
->
https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values-ru/strings.xml

2021-07-31 15:00 UTC, AJenbo commented
@Iniquitatis how do you feel about giving this a quick look?

@AAS I'll make sure to mark the 4 strings correctly

2021-07-31 15:52 UTC, tsunamistate reviewed
Looks good!

Just needs some minor misspelling fixes.
I have also proposed some options for problematic translations

2021-07-31 15:52 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Согутый"
```suggestion
msgstr "Согнутый"
```

2021-07-31 15:52 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Метиоритный"
```suggestion
msgstr "Метеоритный"
```

2021-07-31 15:52 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "огоня"
```suggestion
msgstr "огня"
```

2021-07-31 15:52 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Кепка размышлений"
"Кепка" вообще не нравится
Скорее "Шапка" подойдёт

2021-07-31 15:52 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "восстановить жизнь и ману полнстью"
```suggestion
msgstr "полностью восстановить жизнь и ману"
```

2021-07-31 15:52 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Невозможно открыть фал сохранённой игры"
```suggestion
msgstr "Невозможно открыть файл сохранённой игры"
```

2021-07-31 15:52 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Грубое дьявольское отродье"
Diablo1.ru предлагает "Дьяволёнок"

2021-07-31 15:52 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Убийца"
```suggestion
msgstr "Истребитель"
```

2021-07-31 15:52 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Премещение"
```suggestion
msgstr "Перемещение"
```

2021-07-31 15:52 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Восресить"
```suggestion
msgstr "Воскресить"
```

2021-07-31 16:19 UTC, Iniquitatis requested changes
Looks fine to me, aside from a few typos.

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Темный Лорд"
```suggestion
msgstr "Тёмный Лорд"
```

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Плеточный червь"
```suggestion
msgstr "Плёточный червь"
```

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Пукарат Нечистый"
Puke — блевать.
Блевокрыса? Звучит странно.
Что-то слишком много у Близзов блюющих тварей. Ahem.

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Чёрнострел Пылающий"
```suggestion
msgstr "Чернострел Пылающий"
```
Иначе два ударения в одном слове, либо одно неправильное.

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Череподявол Острокост"
```suggestion
msgstr "Череподьявол Острокост"
```

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Чёрношторм"
```suggestion
msgstr "Черношторм"
```

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Чёрнояз"
```suggestion
msgstr "Чернояз"
```

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Огневедьм Нечистивый"
```suggestion
msgstr "Огневедьм Нечестивый"
```

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Чёрночерен"
```suggestion
msgstr "Черночереп"
```

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Судьбокров"
Судьбоблако!
...
Шутка?

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Уединенный"
```suggestion
msgstr "Уединённый"
```

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Невозможно загрузить персонаж"
```suggestion
msgstr "Невозможно загрузить персонажа"
```
Скорее, родительный падеж.

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +"Убедитесь что devilutionx.mpq находится в папке с игрой и он обновлён."
```suggestion
"Убедитесь, что devilutionx.mpq находится в папке с игрой и он обновлён."
```

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Заряженый болт"
```suggestion
msgstr "Заряженный болт"
```

2021-07-31 16:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Восресить"
```suggestion
msgstr "Воскресить"
```

2021-07-31 17:12 UTC, SourceCodeDeleted commented on Translations/ru.po
> +msgstr "Энергия приходит за счет мудрости"
Can our devikutionx habdle the ё letter? I think in most cases we can just leave it as е .

2021-07-31 17:20 UTC, SourceCodeDeleted commented on Translations/ru.po
> +msgstr "Согутый"
I think согнутый is best here .

2021-07-31 17:23 UTC, SourceCodeDeleted commented on Translations/ru.po
> +msgstr "личя"
Пьявка это leach но , мне меч пьявкы звучит странно )

2021-07-31 17:37 UTC, SourceCodeDeleted commented on Translations/ru.po
> +msgstr "Пукарат Нечистый"
Чего не хочешь назвать его пукрат ?))

Может быть пьюкрат подходит лучше так как , это имя монстера ? 

Я об этом подумал чуть чуть и не могу придумать лучше. Блевокрыса хоть понятное

2021-07-31 17:40 UTC, SourceCodeDeleted commented on Translations/ru.po
> +msgstr "Судьбокров"
Гммм это мне звучит странно .

2021-07-31 17:44 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Энергия приходит за счет мудрости"
@SourceCodeDeleted If that's the case, then we need to be consistent about it. There are already lots of occurrences of "ё" in the latest translation PRs.

2021-07-31 17:45 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "личя"
Точно. Пропустил оригинал. `Lich` vs `leech`.

2021-08-01 04:36 UTC, AAS reviewed
> Would you be willing to also translate the 10 lines for the Android app?
> 
> https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values/strings.xml
> ->
> https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values-ru/strings.xml

Done.
https://github.com/diasurgical/devilutionX/pull/2481

2021-08-01 12:01 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Убийца"
Окей, тогда оставим как есть

2021-08-01 12:40 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Судьбокров"
@AAS Да нет, это я просто оффтопом написал. =) Судбокров, кажется, уже звучит достаточно адекватно.

_Впрочем, я не шибко силён в литературной части и в названиях в частности._

2021-08-01 12:54 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Грубое дьявольское отродье"
@AAS По поводу `Brute`: возможно, `здоровяк` или `громила` (ссылаясь на [одно из значений](https://dictionary.cambridge.org/dictionary/english/brute)).

P.S. Кач**о**к. =)

2021-08-01 12:55 UTC, SourceCodeDeleted commented on Translations/ru.po
> +msgstr "Грубое дьявольское отродье"
Мне нравится громила

2021-08-01 13:01 UTC, SourceCodeDeleted commented
Когда я начал переводить все эти строчки , мне сложно было перевести эти благословения от шрайнов .

2021-08-01 13:08 UTC, SourceCodeDeleted commented
Так как я не могу ответить прямо на все эти вопросы , 
Судьбомес - Я думаю что нормально .
Дьяволёнок  тоже хорошее , а дьяволёнок-качок мне странно звучит )

2021-08-01 19:45 UTC, AJenbo commented
You guys will let me know when this is ready right? Having a hard time following the discussion 😅

2021-08-03 06:24 UTC, AAS commented
@AJenbo All reported issues were fixed. It's done on my end (:

2021-08-03 06:44 UTC, merged

2021-08-03 06:45 UTC, AJenbo commented
Thanks I'll see about the font later this week

2021-08-09 20:12 UTC, SourceCodeDeleted commented on Translations/ru.po
> +msgstr "Энергия приходит за счет мудрости"
@Iniquitatis  yes, I am looking at the pictures uploaded by @AJenbo  and I don't see the **Ё ё**  letters . @AJenbo  is there a E with two dots on it?

Besides, we can read without this letter )

2021-08-09 20:15 UTC, SourceCodeDeleted commented
I just realised this is merged already .... sorry for notifications )

2021-08-09 20:19 UTC, Iniquitatis commented on Translations/ru.po
> +msgstr "Энергия приходит за счет мудрости"
While we can read without it, is there any reason for not adding it? Russian alphabet has more letters than English in any case.

2021-09-24 03:22 UTC, AJenbo commented
@AAS @Iniquitatis @SourceCodeDeleted the Cyrillic font has not been implemented and all reported translation issues addressed. If you have time to update, test and complete the new parts of the translation that would be greatly appreciated as we are planning a release next month :)

![image](https://user-images.githubusercontent.com/204594/134613204-010b1748-0b92-48dd-9077-89974c35c9a9.png)

For testing you can simply fetch the latest test build and put the .mo produced by Poedit in the game folder (set language in diablo.ini)

2021-09-24 16:19 UTC, AAS commented
Oh, that looks awful in UI (:
I'll look into in it tomorrow or the day after.

2021-09-24 18:00 UTC, tsunamistate commented
@AAS @Iniquitatis I have started a branch to unfuzzy and translate the text
https://github.com/tsunamistate/devilutionX/tree/update-ru-translation
Let's cooperate to avoid duplicating effort

2021-09-25 04:32 UTC, AAS commented
@tsunamistate OK, I'll push my fixes into your repo.

2021-09-26 14:45 UTC, SourceCodeDeleted commented
It seems that we probably should truncate some words somehow .

2021-09-26 14:46 UTC, SourceCodeDeleted commented
> Oh, that looks awful in UI (:
> I'll look into in it tomorrow or the day after.

It seems that we probably should truncate some words somehow .

2021-09-26 22:06 UTC, AJenbo commented
You can also break some of them in to two lines

2021-09-27 18:46 UTC, SourceCodeDeleted commented
Sometimes when we want to shorten a word, we do this.

`сопротив.-е`

I think the - and having 
`сопро - 
тивление`

Might not look good. 

@AAS  what do you think?

2021-09-28 02:54 UTC, AAS commented
@SourceCodeDeleted I've never seen anyone used `сопротив.-е` shortening style, it looks odd to me to put `.` before `-`, and we only 2 chars shorter than original word.
Also we can't go with `сопро - тивление` because there is no place for `молнии/огню/магии` in second line.
Right now it's `сопротив молнии/огню/магии` two liner  in @tsunamistate's branch.

2021-09-28 10:01 UTC, tsunamistate commented
@AAS @SourceCodeDeleted made a draft PR based on current branch state of my fork: https://github.com/diasurgical/devilutionX/pull/2970
So let's continue discussion there