Add debug text commands
diasurgical/devilutionX pull request #2601
Opened 2021-08-14 12:32 UTC by obligaron

### Intro

This PR introduces something like a debug `console`.
In debug mode you can write chat text and this will be analyzed by `CheckDebugTextCommand`.
For this change it was necessary to allow chat in singleplayer (only in debug).
Change is inspired by @qndel #2128. 🙂 

<details><summary>Example Usage Video</summary>

https://user-images.githubusercontent.com/25415264/129446094-1dba7f03-29e8-45f4-a1ce-2e2dfe195ff1.mp4

</details>

### Notes
- Works only in debug and is not in production/release version.
- This PR lays the groundwork to easily add more debug commands.
- With this PR only some commands are realized. This list can be expanded in followup PRs.
- Many commands that are available per debug text commands have currently hard coded keys (for example `lvl up` command). The discussion if we want to have this hard coded keys remaining or not is not part of this pr.
- This PR introduces `warp to lvl`, `reset lvl` and `godmode` toggle.
- Includes help command 😉 
- It's also possible to use `QuickMessage` and debug text commands together. So only one click for godmode. 😜

2021-08-14 12:58 UTC, AJenbo commented
Reset level seams particularly useful

2021-08-14 13:50 UTC, qndel commented on Source/debug.cpp
> +		return fmt::format("Level {} is not known. Do you want to write a extension mod?", level);
```suggestion
		return fmt::format("Level {} is not known. Do you want to write an extension mod?", level);
```
😆

2021-08-14 13:51 UTC, qndel commented on Source/debug.cpp
> +		return fmt::format("I did nothing but fulfilled you wish. You are already at level {}.", level);
```suggestion
		return fmt::format("I did nothing but fulfilled your wish. You are already at level {}.", level);
```

2021-08-14 14:22 UTC, obligaron commented on Source/debug.cpp
> +		return fmt::format("Level {} is not known. Do you want to write a extension mod?", level);
fixed 🙂

2021-08-14 14:22 UTC, obligaron commented on Source/debug.cpp
> +		return fmt::format("I did nothing but fulfilled you wish. You are already at level {}.", level);
fixed 🙂

2021-08-18 18:02 UTC, qndel requested changes
Make commands in /cmd or /cmd<space><params> format
Remove text displayed after executing commands
No space in commands themselves 
Other than that, can't wait to merge and add more 🤤

2021-08-19 00:53 UTC, AJenbo approved these changes
No comment, well other then this being awesome :)

Being a Quake fan I might have a long term goal of having this work via a drop down terminal :D

2021-08-19 00:58 UTC, julealgon commented
Cool to see this idea added in. Obvious and useful improvement.

2021-08-19 01:34 UTC, AJenbo approved these changes
I partially addressed @qndel comment.

- Commands are now simulating one word with arguments (this way they will stay the same once we make them more flexible.
- They are now closer in name and style to what Quake uses

I did not prefix them with / for 2 reason
- Quake doesn't do this
- If we move to a debug console this won't be needed any way
- We do not map / in our crappy keyboard handeling so it would be impossible to type

2021-08-19 01:38 UTC, julealgon commented
We should make this separate from ingame chat at some point BTW.

2021-08-19 01:40 UTC, AJenbo commented
Another idea we can lift from Quake is to remove the application arguments and instead allow the application to take generic console commands as an argument:

`devilutionx +god` would start the game in god mode, this also removes a bunch of specialized code and coupling.

> We should make this separate from ingame chat at some point BTW.

Yep, see my other comments regarding a Quake style console :D

2021-08-19 01:44 UTC, merged