Spanish translation: All short text corrected
diasurgical/devilutionX pull request #2675
Opened 2021-08-23 00:05 UTC by hiperiondev

2021-08-23 13:34 UTC, NikoVP commented on Translations/es.po
> +msgstr "Vofre"
```suggestion
msgstr "Cofre"
```

2021-08-23 13:35 UTC, NikoVP commented on Translations/es.po
>  msgstr "{:s} Santuario"
```suggestion
msgstr " Santuario de {:s}"
```

2021-08-23 13:37 UTC, NikoVP commented on Translations/es.po
> +msgstr "Libro del Ciego"
```suggestion
msgstr "Libro de los Ciegos"
```

2021-08-23 13:39 UTC, NikoVP commented on Translations/es.po
>  msgstr "Primavera Purificante"
```suggestion
msgstr "Manantial Purificante"
```

2021-08-23 13:40 UTC, NikoVP commented on Translations/es.po
> +msgstr "Santuario de la Cabra"
```suggestion
msgstr "Santuario de las Cabras"
```

2021-08-23 13:44 UTC, NikoVP commented on Translations/es.po
>  msgstr "Stand de Villa"
```suggestion
msgstr "Vil Estante"
```

2021-08-23 13:45 UTC, NikoVP commented on Translations/es.po
>  msgstr "Atrapado {:s}"
```suggestion
msgstr "{:s} Atrapado"
```

2021-08-23 13:47 UTC, NikoVP commented on Translations/es.po
>  msgstr "Habla con Griswold"
```suggestion
msgstr "Hablar con Griswold"
```

2021-08-23 13:48 UTC, NikoVP commented on Translations/es.po
>  msgstr "Habla con Adria"
```suggestion
msgstr "Hablar con Adria"
```

2021-08-23 13:50 UTC, NikoVP commented on Translations/es.po
>  msgstr "Habla con Wirt"
```suggestion
msgstr "Hablar con Wirt"
```

2021-08-23 13:51 UTC, NikoVP commented on Translations/es.po
>  msgstr "Habla con Cain"
```suggestion
msgstr "Hablar con Cain"
```

2021-08-23 14:00 UTC, NikoVP commented on Translations/es.po
> +msgstr "Tuerca Completa"
```suggestion
msgstr "Chiflado Completo"
```

2021-08-23 14:06 UTC, NikoVP commented on Translations/es.po
> +msgstr "Puntos de Golpe: {:d}- {:d}"
```suggestion
msgstr "Vida: {:d}- {:d}"
```

2021-08-23 14:20 UTC, NikoVP requested changes
Hola, no soy nativo así no que puedo échate una mano directamente. Aún quedan muchísimas cosas a revisar, varios términos siguen mal traducidos tras la revisión. Te recomiendo usar Wikipedia y otras fuentes para comprobar que realmente significan las palabras y echar vistazo a otras traducciones. También te puedes unir al canal de DeviutionX en Discord. Hay otra persona que empezó la traducción en español y no la termino, quizás la puedes usar como referencia.  Ven al canal y podamos charlar y resolver algunas dudas que tienes. Un saludo!

2021-08-23 17:34 UTC, hiperiondev commented
Gracias por ayudar.
En la traducción voy poniendo notas donde no estoy seguro. En muchos casos es dificil sin contexto.
Estoy terminando de revisar los dialogos que son bastante largos.
Es complicado para hacerlo solo y sin un feedback.
Cuando complete los dialogosvoy a ir a Discord a ver si se suma alguien más

2021-08-23 18:13 UTC, hiperiondev commented
Tambien voy a revisar la traducción en Italiano, ya que es mi segunda lengua. No se en que estado está

2021-08-23 19:50 UTC, NikoVP commented
Entonces estas traduciendo sin mucho conocimiento de Inglés?

2021-08-24 00:29 UTC, hiperiondev commented
Tengo conocimiento de lectura tecnica, pero aquí hay varias cosas que me exceden.
El portugues lo leo bastante bien. Incluiré esa revisión tambien.

Muchas gracias

2021-08-24 08:47 UTC, NikoVP approved these changes

2021-08-24 09:05 UTC, AJenbo commented
@NikoVP I see that you approved the changes, but it does not appear that @hiperiondev has applied your suggestions? Normally you do not approve before the requested changes have been made or you guys agreed to handle it differently.

Let me know if I should merge as is, apply the suggested changes (Preferably @hiperiondev would accept them so that we all agree) and merge, or something else.

2021-08-24 12:54 UTC, NikoVP commented
Don´t know what hiperiondev plan is but probably the whole translation will need additional passes to get it to better shape. His corrections now improve some parts of it so its okay to commit. I'll refrain from correcting myself since its not my first or second language, Hopefully someone native will join in and do some more editing until 1.3.0 release comes.

2021-08-24 13:47 UTC, hiperiondev commented
I'm not sure whether to add these suggestions in this commit or add them to the next one, maybe the latter is better and disregard this one.
Today I plan to finish the texts of the conversations and go over everything again. Possibly at night (here UTC -3) I could send the corrected ending.
In the translation I added many comments about parts that I am not sure or do not know how to translate.
After this it would be important that others join in to provide corrections so I am going to Discord with the hope that some charitable soul wants to collaborate.

2021-08-24 13:50 UTC, hiperiondev commented
As I have told @NikoVP my second language is Italian so I plan to compare the translations that I do not consider correct against this translation. I can also use the Portuguese translation as I read it very well.
I think it can be a good alternative while we wait for someone else to join the project.

2021-08-24 14:07 UTC, hiperiondev commented
For now, and being the only translator available, my plan is to release the corrections in steps and return to the beginning in different passes to refine the corrections.
In this way, the translation will be improved incrementally so that players can use it and find context errors. Hopefully we will start to get some very important feedback to continue.

2021-08-24 14:10 UTC, hiperiondev commented
It would be interesting if the game itself had some indication on how to report translation errors so that players who do not know about programming know where to report them

2021-08-24 17:30 UTC, AJenbo commented
If you agree with the suggestions you can simply add them by going to the file changes tab and click "Add suggestion to batch", and then commit them to the pull request.

![image](https://user-images.githubusercontent.com/204594/130662480-ebc30a78-bb6b-4f53-9039-1cd14b7034de.png)

You can also commit individual suggestion directly here in the overview, or write reply if you do not agree with the suggestion.
That is the preferred way to handle pull requests.

2021-08-24 17:32 UTC, AJenbo commented
@inukaze has also been working on a Spanish translation, maybe he would be willing to help. He is also on Discord.

2021-08-24 20:43 UTC, hiperiondev commented
I've added @NikoVP's suggestions to the next commit.
I will close this one so as not to create conflicts.

2021-08-24 20:43 UTC, closed without merging

2021-08-24 20:43 UTC, hiperiondev commented
It is continued in the next commit

2021-08-24 21:47 UTC, AJenbo commented
Ok, you actually do not need to close the PR to update it you simply push your changes and the PR will update :)

2021-09-07 19:27 UTC, inukaze commented
> @inukaze has also been working on a Spanish translation, maybe he would be willing to help. He is also on Discord.

Thanks, well i don't know the notification just arrive today. but yes, i had my own spanish translation finished three months ago. i just waiting the next windows release to put the spanish translation for give a copy to my friends to play the game with my spanish text translation.

2021-09-07 19:30 UTC, AJenbo commented
You don't want to have it included in the release?

2021-09-08 20:43 UTC, inukaze commented
@Ajenbo : i had strange bug if i translate "Resist Magic" (ID : 1316) to "Rest. Magica" / "Magica" / "Magicka" the Devilution Client or hang up or make a segmentation fault. 

The most accurate translation of "Resist Magic" to spanish is "Resistencia Magica" but is too long, because of that i use the abreviature "Rest." but the error looks like is something character quantity, because if i add "Rest. Magia1" i got same error. and is just adding one character more. 

Well i should leave the translation with "Rest. Magia" is not right but the spanish speakers goes to think "Resistencia a la magia".