Add PlayerId param to methods needed by couch-coop
diasurgical/devilutionX pull request #2958
Opened 2021-09-26 20:57 UTC by yuripourre

2021-09-26 22:36 UTC, AJenbo requested changes
I'm not sure all the changes here make sens, rather they just change any occurrence of MyPlayerId, and without changing the name of related variable.

I would suggest initially only changing what is needed to gain individual control of players, and then deal with the UI portion at a later point.

2021-09-26 22:36 UTC, AJenbo commented on Source/control.cpp
> +	auto &myPlayer = Players[playerId];
Rename `myPlayer` to `player`

2021-09-26 22:36 UTC, AJenbo commented on Source/control.cpp
> +void DrawLifeFlaskUpper(const Surface &out, int playerId)
Considering that this UI isn't multi user friendly I don't see the point in making it multi user capable?

2021-09-27 02:22 UTC, yuripourre commented on Source/control.cpp
> +	auto &myPlayer = Players[playerId];
Thanks!

2021-09-27 02:24 UTC, yuripourre commented on Source/control.cpp
> +void DrawLifeFlaskUpper(const Surface &out, int playerId)
Right, I will convert the PR into draft, this is more like a POC to me. I am still creating a strategy to have the couch-coop working. I think I will be working on this until I have it fully working (including UI), then I will slice it into smaller manageable PRs.

Thanks for reviewing

2021-12-27 05:21 UTC, closed without merging

2021-12-27 06:40 UTC, AJenbo commented
I think the preferred way to move forward with this is to start making player specific operations members of the player struct so that they operate with in the context of the given player. This will also naturally happen in a gradual (but a bit slow atm) fashion.

The UI is starting to be more dynamic which should make some of the work on coop support easier.

2021-12-27 09:46 UTC, yuripourre commented
@AJenbo this approach would be ideal, for sure. I see the code improving over time, I have a really good time watching the progress. I will probably try to implement it again in the future.