Polish translation update part1
diasurgical/devilutionX pull request #2996
Opened 2021-09-30 20:15 UTC by zutmkr

First part of translation. Lets review it together and see if we can make it better.

2021-09-30 21:39 UTC, qndel requested changes

2021-09-30 21:39 UTC, qndel commented on Translations/pl.po
> +msgstr "Wszystkie komputery muszą być połączone siecią kompatybilną z TCP."
```suggestion
msgstr "Wszystkie komputery muszą być połączone z siecią kompatybilną z TCP."
```

2021-09-30 21:39 UTC, qndel commented on Translations/pl.po
> +msgid "  nor GOG.com. Neither Blizzard Entertainment or GOG.com has not tested"
to cofnij

2021-09-30 21:39 UTC, qndel commented on Translations/pl.po
> +msgstr "Miecz sprawiedliwości jest szybki i ostry!"
```suggestion
msgstr "Miecz sprawiedliwości jest szybki i ostry"
```

2021-09-30 21:39 UTC, qndel commented on Translations/pl.po
> +msgstr "Energia jest kosztem mądrości"
```suggestion
msgstr "Energia kosztem mądrości"
```

2021-09-30 21:39 UTC, qndel commented on Translations/pl.po
> +msgstr "Chciwość zawodzi, cierpliwość popłaca"
```suggestion
msgstr "Gdzie chciwość zawodzi, tam cierpliwość popłaca"
```

2021-09-30 21:39 UTC, qndel commented on Translations/pl.po
> +msgstr "Brakuje reszty plików MPQ do Hellfire"
```suggestion
msgstr "Brakuje części plików MPQ do Hellfire"
```

2021-09-30 21:39 UTC, qndel commented on Translations/pl.po
> +msgstr "Nie udało się utworzyć nowego okna"
```suggestion
msgstr "Nie udało się utworzyć głównego okna"
```

2021-09-30 21:39 UTC, qndel commented on Translations/pl.po
> +msgid "Gryphons Claw"
cofnij zmianę

2021-09-30 21:39 UTC, qndel commented on Translations/pl.po
> +msgid "Helm of Sprits"
też cofnij

2021-10-01 09:23 UTC, zutmkr commented on Translations/pl.po
> +msgid "  nor GOG.com. Neither Blizzard Entertainment or GOG.com has not tested"
```suggestion
msgid "  nor GOG.com. Neither Blizzard Entertainment nor GOG.com has tested"
```

2021-10-01 09:30 UTC, zutmkr commented on Translations/pl.po
> +msgid "Helm of Sprits"
```suggestion
msgid "Helm of Spirits"
```

2021-10-01 09:30 UTC, zutmkr commented on Translations/pl.po
> +msgid "Gryphons Claw"
```suggestion
msgid "Gryphon's Claw"
```

2021-10-04 09:20 UTC, merged

2021-10-04 10:19 UTC, AJenbo commented
:+1:

2022-03-31 01:04 UTC, AJenbo commented
@zutmkr if you have time to update the translation now would be a good time to make it for the next release :)

There are about 250 lines that needs an update.