barb & bard TRNs
diasurgical/devilutionX pull request #4076
Opened 2022-02-20 14:21 UTC by qndel

Draft till actual TRNs for barb/bard get chosen

2022-05-10 22:45 UTC, qndel commented
@glebm Wondering if https://github.com/diasurgical/devilutionX/pull/4076/commits/6c6bb906f80874eaaaeabbe64209275a49482463 is fine, I'm not a template expert 😅 not sure if there won't be any conflict between 
```cpp
template <typename T, bool isOptional = false>
```
and
```cpp
template <typename T, std::size_t N>
```
since bool can be treated as size and the opposite.

I'm just hoping 
```cpp
template <typename T, std::size_t N>
void LoadFileInMem(const char *path, std::array<T, N> &data)
```
arguments for that function are distinguishable enough that there won't be any confusion
Do you have any idea how to handle it in a more elegant way? Ideally some type like bool that doesn't convert to a number :D

2022-05-11 06:23 UTC, glebm commented
It's fine but perhaps let's add a `LoadFileInMem(SDL_RWops *, ...)` instead?

2022-06-05 09:42 UTC, AJenbo commented on Source/player.cpp
> +			Cl2ApplyTrans(directionFrames[i], reinterpret_cast<std::array<uint8_t, 256> &>(trn[0]), (int)directionFrames[i][0]);
Don't use c-style casting

2022-06-06 22:04 UTC, glebm commented on Source/player.cpp
> +			Cl2ApplyTrans(directionFrames[i], reinterpret_cast<std::array<uint8_t, 256> &>(trn[0]), static_cast<int>(directionFrames[i][0]));
Previously we didn't have a `Cl2ApplyTrans` here for warrior/rogue/etc.
Why apply these now? For modding?

2022-06-06 22:04 UTC, glebm approved these changes

2022-06-06 22:05 UTC, glebm commented on Source/player.cpp
> +			Cl2ApplyTrans(directionFrames[i], reinterpret_cast<std::array<uint8_t, 256> &>(trn[0]), static_cast<int>(directionFrames[i][0]));
Nevermind, I've now read the PR description :smile:

2022-06-06 22:06 UTC, glebm commented on Source/player.cpp
> +	auto trn = GetClassTRN(player);
```suggestion
	std::unique_ptr<uint8_t[]> trn = GetClassTRN(player);
```

2022-06-06 22:07 UTC, glebm requested changes

2022-06-06 22:07 UTC, glebm commented on Source/player.cpp
> +			Cl2ApplyTrans(directionFrames[i], reinterpret_cast<std::array<uint8_t, 256> &>(trn[0]), static_cast<int>(directionFrames[i][0]));
This is a very unsafe cast!

Let's make `GetClassTRN` return an `std::array<uint8_t, 256>` instead.

2022-06-07 07:38 UTC, glebm submitted a review, later dismissed

2022-08-10 22:23 UTC, glebm approved these changes

2022-08-10 23:02 UTC, merged