Russian translation update
diasurgical/devilutionX pull request #4327
Opened 2022-04-03 16:14 UTC by SergBrNord

1. Now translated 2018 lines from 2018.
2. Fixed weird translation of titles.
3. Some lines are now closer in meaning to the original.
4. Some strings are now adapted to interface restrictions.

2022-04-03 16:36 UTC, AJenbo commented
Thanks, but it looks like you based it on a translation that is 3 months old at this point.

Please do not add the short cut keys in the translation, they might not fit and it's possible to change the keys in settings, and they do not apply when using touch or a gamepad.

I can try and help with updating the file, but since there are a lot of changes it might be best if you could do it since I do not speak Russian and can't evaluate the changes.

2022-04-03 16:45 UTC, tsunamistate commented
Please hold on merging this - reviewing

2022-04-03 16:49 UTC, AJenbo commented
> Please hold on merging this - reviewing

I'm not able to review this PR because it is in conflict with the other translations that have been done since January. Some one needs to transfer all the good parts to an updated file.

I have transferred the new lines to this PR: https://github.com/diasurgical/devilutionX/pull/4328 If you can give that a quick look then we can merge that. Hopefully @SergBrNord can transfer the rest later.

2022-04-03 17:22 UTC, tsunamistate requested changes
Just some minor nits here and there

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Задания"
Текст еле помещается, ИМХО прошлый вариант лучше

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "1 - 8: Использовать предмет на поясе."
```suggestion
msgstr "Использовать предмет на поясе."
```
Не используй указания на горячие клавиши, это просто дубликат, и в меню кнопку можно поменять
![image](https://user-images.githubusercontent.com/4958520/161439346-d1c777d6-aa59-41ca-b838-436b4cb08a81.png)

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "F5, F6, F7, F8:     Установить горячую клавишу для заклинания."
```suggestion
msgstr "Установить горячую клавишу для заклинания."
```

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Лвл {} {}"
Уж лучше от русского делать сокращение
```suggestion
msgstr "Ур {} {}"
```

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
>  msgstr "{0} {1}"
{2} пропущено

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
> +msgstr " {:d} Сила"
Если так, то надо склонять
```suggestion
msgstr " {:d} Силы"
```

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Играйть в Diablo или Hellfire."
```suggestion
msgstr "Играть в Diablo или Hellfire."
```
:)

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
>  msgstr "Перейти в Shareware"
Restrict =/= Перейти
Уж лучше "Ограничить до Shareware"

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Показан вступительный ролик."
Shown здесь в роли имени прилагательного, "Показываемый ролик"

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Показана заставка."
Имя прилагательное, "Показываемая заставка"

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Тестировать варваа"
```suggestion
msgstr "Тестировать варвара"
```
Видно, уже были замыленные глаза :)

2022-04-03 17:22 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Быстрая атака"
"Быстрое заклинание"?

2022-04-03 17:26 UTC, tsunamistate commented
> I have transferred the new lines to this PR: https://github.com/diasurgical/devilutionX/pull/4328 If you can give that a quick look then we can merge that.

I'll transfer my comments there
What happens with this PR then?

2022-04-03 17:29 UTC, AJenbo commented
>  What happens with this PR then?

That's up to @SergBrNord

2022-04-03 17:31 UTC, tsunamistate commented
Note to @SergBrNord for the future:
Assuming you're using POEdit, do "Update from code", save the file and commit it first, to make a separate commit that only has source line changes. That way, it's easier to see new and/or changed text by ignoring first commit.

2022-04-03 17:34 UTC, tsunamistate commented
I think there's no need for #4328 , @SergBrNord just update from code and rebase
Email me if you don't know how

2022-04-03 18:40 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "Фоновые вокалисты mr. Dabiri"
1. На тот момент показалось, что будет лучше. Впрочем, варианты равнозначны, кроме размера строк.
2. Буду иметь ввиду

2022-04-03 18:42 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "Создать открытую игру"
Не заметил, хотя вроде проверял.

2022-04-03 18:42 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "Программное обеспечение"
Да, это так, но я решил перевести ближе к оригиналу.

2022-04-03 18:43 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "Присоединиться к игре"
И здесь тоже не заметил.

2022-04-03 18:44 UTC, AJenbo commented
@SergBrNord you need to first merge or rebase from master. If you are not used to Git or merging conflicts you can also download the latest pot template and use that to update the translation file. Then I can rebase and @tsunamistate can review it.

https://raw.githubusercontent.com/diasurgical/devilutionX/master/Translations/devilutionx.pot

2022-04-03 18:46 UTC, SergBrNord commented on Translations/ru.po
> +# Непонятно, где используется, но привёл в соответсвие с остальным.
Странно, я уверен, что у меня было 2 вхождения в файле. Причём в одной группе строк "Spells" было переведено как "Магия", а во второй как "Заклин".

2022-04-03 18:49 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Программное обеспечение"
Программное обеспечение - software
Разработка программного обеспечения - Software Engineering

Всё правильно было в оригинале

2022-04-03 18:50 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "Задания"
Помещается же, всё-таки задания по смыслу намного ближе, чем журнал. В контексте RPG, понятно что там находится, но...

2022-04-03 18:51 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "1 - 8: Использовать предмет на поясе."
Указания на клавиши уже были в файле до меня. Всё, что я сделал - поставил точку. Я смотрел и думал, не убрать ли мне их везде, где не в оригинале, но решил в итоге не трогать.

2022-04-03 18:52 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "F5, F6, F7, F8:     Установить горячую клавишу для заклинания."
То же, что и выше.

2022-04-03 18:52 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "Лвл {} {}"
Согласен.

2022-04-03 18:54 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "1 - 8: Использовать предмет на поясе."
Лучше убери где в оригинале нет указаний

2022-04-03 18:56 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Задания"
Ладно, пусть останется твой вариант

2022-04-03 18:58 UTC, AJenbo commented on Translations/ru.po
> +msgstr "1 - 8: Использовать предмет на поясе."
There where probably put there by Poedit by copying a different translation when updating the file from an older version with different texts.

2022-04-03 19:02 UTC, SergBrNord commented on Translations/ru.po
> +msgstr " {:d} Сила"
Я посмотрел на соседние и решил, что там подразумевается именительный падеж, единственное число. Согласен.

2022-04-03 19:03 UTC, SergBrNord commented on Translations/ru.po
>  msgstr "Перейти в Shareware"
Да, так будет значительно лучше.

2022-04-03 19:06 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "Тестировать варваа"
Всё, так я отсмотрел большую часть из 2018 строк, кроме текста заданий.

2022-04-03 19:06 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "Показан вступительный ролик."
В принципе, с учётом того, что я переводил настройки, можно было понять, но я не смог.

2022-04-03 19:07 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Тестировать барба"
```suggestion
msgstr "Тестировать барда"
```

2022-04-03 19:07 UTC, SergBrNord commented on Translations/ru.po
> +msgstr "Быстрая атака"
А влезет? Если влезет, то лучше не мой вариант.

2022-04-03 19:11 UTC, tsunamistate commented on Translations/ru.po
> +msgstr "Быстрая атака"
Влезет :)
![image](https://user-images.githubusercontent.com/4958520/161444133-19348413-6d43-4b82-9df8-1cf67359911f.png)

2022-04-03 19:20 UTC, AJenbo commented on Translations/ru.po
> +msgstr "Тестировать варваа"
There are 2042 lines now. Please update the file. Some of the tests here are no longer in the current file.

2022-04-03 19:26 UTC, SergBrNord commented
I use GitHub for the second time in my life. So, I'm trying...

2022-04-03 19:39 UTC, tsunamistate commented
@SergBrNord are you using Github web interface?
It would be better, and easier to use dedicated editor for this, like POEdit: https://poedit.net/
Use its "Update from code" feature, save and commit it to your branch
https://docs.github.com/en/get-started/using-git/pushing-commits-to-a-remote-repository

Anders will then take care of the rest

2022-04-03 19:45 UTC, AJenbo commented
> Use its "Update from code" feature, save and commit it to your branch https://docs.github.com/en/get-started/using-git/pushing-commits-to-a-remote-repository

This was already done, but it is not enough. You also need to update the code first or it will just be updating to the old code from January.

If you are new to git it's going to be difficult to update the code as there will be conflicts in the ru.po file. This is why I suggest downloading https://raw.githubusercontent.com/diasurgical/devilutionX/master/Translations/devilutionx.pot instead and using that to update (In the menu select `Translation`->`Update from POT file...`).

2022-04-03 20:25 UTC, SergBrNord commented
Now better? =)

2022-04-03 21:02 UTC, AJenbo commented
@SergBrNord @tsunamistate I have updated this branch so that it can now be reviewed and merged properly. @SergBrNord you should do a pull on your computer before making any changes.

2022-04-03 21:16 UTC, AJenbo commented on Translations/ru.po
>  msgstr "Козлиный храм"
```suggestion
msgstr "Козье святилище"
```

2022-04-05 00:59 UTC, AJenbo commented
@tsunamistate let me know when this is ready to be merged :)

2022-04-05 07:13 UTC, tsunamistate approved these changes
LGTM, good to merge

2022-04-05 07:50 UTC, merged