Prefer system FindSDL_audiolib
diasurgical/devilutionX pull request #4464
Opened 2022-04-17 02:29 UTC by SuperSandro2000

2022-04-17 06:21 UTC, glebm requested changes

2022-04-17 06:21 UTC, glebm commented on CMake/finders/FindSDL_audiolib.cmake
> +  add_library(SDL2::SDL_audiolib UNKNOWN IMPORTED)
1. `SDL_audiolib` is not a part of SDL2; The name should be `SDL_audiolib::SDL_audiolib`
2. In 3rdParty/SDL_audiolib/CMakeLists.txt, add `add_library(SDL_audiolib::SDL_audiolib ALIAS SDL_audiolib)`
3. Use `SDL_audiolib::SDL_audiolib` as the dependency name throughout.

2022-04-17 06:21 UTC, glebm commented on CMake/Dependencies.cmake
> +    include_directories(${SDL_audiolib_INCLUDE_DIR})
The imported package already defines `INTERFACE_INCLUDE_DIRECTORIES`, this is not necessary.

2022-04-17 09:59 UTC, tsunamistate commented
I don't know if this is needed.
Is SDL_Audiolib provided in any of Linux distributions as a package?

2022-04-17 19:20 UTC, SuperSandro2000 commented
> I don't know if this is needed. Is SDL_Audiolib provided in any of Linux distributions as a package?

Yes, it is by nixpkgs/NixOS

2022-04-21 11:10 UTC, SuperSandro2000 commented
Force pushed the requested changes. I hope I didn't miss anything. My CMake knowledge could be better.

2022-06-07 07:22 UTC, glebm requested changes
Looks good overall apart from a couple of formatting issues

2022-06-07 07:22 UTC, glebm commented on CMake/Dependencies.cmake
> +	find_package(SDL_audiolib QUIET)
This is a tab but should be 4 spaces

2022-06-07 07:22 UTC, glebm commented on CMake/finders/FindSDL_audiolib.cmake
> +
Extra blank line at the end of file

2022-06-08 05:37 UTC, AJenbo commented on CMake/finders/FindSDL_audiolib.cmake
> +
```suggestion
```

2022-06-08 05:37 UTC, AJenbo commented on CMake/Dependencies.cmake
> +	find_package(SDL_audiolib QUIET)
```suggestion
    find_package(SDL_audiolib QUIET)
```

2022-06-08 05:38 UTC, merged