Floating numbers
diasurgical/devilutionX pull request #4580
Opened 2022-05-15 21:18 UTC by qndel

2022-05-17 06:24 UTC, glebm commented on Source/qol/floatingnumbers.cpp
> +		DrawString(out, floatingNum.text, endPos, floatingNum.style);
We use CEL for fonts now and CEL has a handy `CelBlitOutlineTo` method that is much faster than rendering 4 times. Let's add outline support to `DrawString` using `CelBlitOutlineTo`?

2022-05-17 18:33 UTC, glebm requested changes

2022-05-17 18:33 UTC, glebm commented on Source/qol/floatingnumbers.cpp
> +UiFlags ShiftIndex(int index)
Perhaps `IndexToFlag`?

2022-05-17 18:33 UTC, glebm commented on Source/qol/floatingnumbers.cpp
> +	double angle = (500 + rand() % 500) * 0.0062831853;
What's 0.0062831853? (please add a comment)

2022-05-19 15:39 UTC, glebm submitted a review, later dismissed

2022-05-19 18:05 UTC, qndel commented
turns out the "optimization" commit broke things a bit - numbers moved slower if you moved towards them and faster if you moved away from them :D it looked bad lol - position needs to be checked every frame for accurate drawing = reverted "optimization"

2022-05-20 17:00 UTC, StephenCWills requested changes

2022-05-20 22:35 UTC, AJenbo commented
why so many options :cry: I think it would be best if the colors where the same for all players so that screen shots will make sens :roll_eyes:

2023-01-01 12:21 UTC, closed without merging