Use _item_indexes types for item_index variables/parameters
diasurgical/devilutionX pull request #5390
Opened 2022-10-02 14:45 UTC by ephphatha

Started out as an attempt to dedupe the two item initialisation routines... There were a few unnecessary transformations through the call chains exposed by that attempt though so split out this PR.

2022-10-09 20:09 UTC, StephenCWills requested changes

2022-10-09 21:05 UTC, ephphatha commented on Source/items.cpp
> +	for (std::underlying_type_t<_item_indexes> i = IDI_WARRIOR; i <= IDI_LAST && AllItemsList[i].iLoc != ILOC_INVALID; i++) {
Thanks for catching this :D

2022-10-11 02:07 UTC, StephenCWills approved these changes

2022-10-11 12:34 UTC, ephphatha commented
Needed to rebase since I introduced a conflict with the other recent PR

2022-10-11 16:51 UTC, merged