Remove "Zen" hit recovery
diasurgical/devilutionX pull request #5724
Opened 2023-01-25 19:23 UTC by ikonomov

I have always perceived this mechanic to be a bug or an oversight that Blizzard simply didn't need to care about.  Gameplay wise it makes no perceivable difference.  My reasoning is that the description of Harmony says "Fastest", clearly implying that this is the fastest recovery bonus that is attainable for a given character and also an indication that the bonus from these affixes is not cumulative.

2023-01-25 19:38 UTC, ikonomov commented
... And course the test would fail, because there is a test specifically for testing Zen mode.  XD I think it must be the name, it sounds cool therefore it must be.

2023-01-25 19:44 UTC, kphoenix137 commented
I think it's evident that this zen mode wasn't intentional since there is no stacking with other combinations. Just a result of graphics and game logic being intertwined

2023-01-25 20:51 UTC, ikonomov commented
There is also this test info for Zen that should perhaps be changed to Harmony.  No idea how to do it.  https://github.com/diasurgical/devilutionX/blob/63577da9eec849f484979d494d5302925661bcba/test/animationinfo_test.cpp#L411

2023-01-25 20:58 UTC, ikonomov commented
@obligaron Would really appreciate your help figuring this out. : )

2023-01-26 01:51 UTC, kphoenix137 commented
`TEST(AnimationInfo, HitRecoverySorcererHarmony) // Skipped frames and ignored delay for last Frame should be considered by distribution logic
{
    RunAnimationTest(
        {
            new SetNewAnimationData(8, 1, AnimationDistributionFlags::None, 3),
            new RenderingData(0.0f, 0),
            new RenderingData(0.3f, 0),
            new RenderingData(0.6f, 0),
            new RenderingData(0.8f, 1),
            new GameTickData(4, 0),
            new RenderingData(0.0f, 1),
            new RenderingData(0.3f, 2),
            new RenderingData(0.6f, 2),
            new RenderingData(0.8f, 2),
            new GameTickData(5, 0),
            new RenderingData(0.0f, 3),
            new RenderingData(0.3f, 3),
            new RenderingData(0.6f, 4),
            new RenderingData(0.8f, 4),
            new GameTickData(6, 0),
            new RenderingData(0.0f, 4),
            new RenderingData(0.3f, 5),
            new RenderingData(0.6f, 5),
            new RenderingData(0.8f, 6),
            new GameTickData(7, 0),
            new RenderingData(0.0f, 6),
            new RenderingData(0.3f, 6),
            new RenderingData(0.6f, 7),
            new RenderingData(0.8f, 7),
            // Animation stopped cause PM_DoGotHit would stop the Animation "if (plr[pnum].AnimInfo.currentFrame >= plr[pnum]._pHFrames) {"
        });`
        
       Add to animationinfo_test.cpp to replace the zen test

2023-01-26 02:04 UTC, kphoenix137 requested changes
```TEST(AnimationInfo, HitRecoverySorcererHarmony) // Skipped frames and ignored delay for last Frame should be considered by distribution logic
{
	RunAnimationTest(
	    {
	        new SetNewAnimationData(8, 1, AnimationDistributionFlags::None, 3),
	        new RenderingData(0.0f, 0),
	        new RenderingData(0.3f, 0),
	        new RenderingData(0.6f, 0),
	        new RenderingData(0.8f, 1),
	        new GameTickData(4, 0),
	        new RenderingData(0.0f, 1),
	        new RenderingData(0.3f, 2),
	        new RenderingData(0.6f, 2),
	        new RenderingData(0.8f, 2),
	        new GameTickData(5, 0),
	        new RenderingData(0.0f, 3),
	        new RenderingData(0.3f, 3),
	        new RenderingData(0.6f, 4),
	        new RenderingData(0.8f, 4),
	        new GameTickData(6, 0),
	        new RenderingData(0.0f, 4),
	        new RenderingData(0.3f, 5),
	        new RenderingData(0.6f, 5),
	        new RenderingData(0.8f, 6),
	        new GameTickData(7, 0),
	        new RenderingData(0.0f, 6),
	        new RenderingData(0.3f, 6),
	        new RenderingData(0.6f, 7),
	        new RenderingData(0.8f, 7),
	        // Animation stopped cause PM_DoGotHit would stop the Animation "if (plr[pnum].AnimInfo.currentFrame >= plr[pnum]._pHFrames) {"
	    });```

2023-01-26 02:15 UTC, ikonomov commented
Thank you KP!

2023-01-27 23:28 UTC, AJenbo commented on Source/player.cpp
> -	if (HasAllOf(player._pIFlags, ZenFlags)) { // if multiple hitrecovery modes are present the skipping of frames can go so far, that they skip frames that would skip. so the additional skipping thats
Also remove the `ZenFlags` definition

2023-01-28 21:27 UTC, AJenbo approved these changes

2023-01-30 18:12 UTC, kphoenix137 approved these changes

2023-01-30 18:15 UTC, merged