Fix loading new demo files and give better error messages when failing
diasurgical/devilutionX pull request #6408
Opened 2023-07-23 22:42 UTC by AJenbo

2023-07-23 23:39 UTC, StephenCWills requested changes

2023-07-23 23:39 UTC, StephenCWills commented on Source/engine/demomode.cpp
> +	diablo_quit(1);
```suggestion
	printNewlineInConsole();
	diablo_quit(1);
```

2023-07-23 23:39 UTC, StephenCWills commented on Source/engine/demomode.cpp
> +		printInConsole("Unsuported Demo version");
```suggestion
		printInConsole("Unsupported Demo version");

```

2023-07-24 00:45 UTC, AJenbo commented
You already reviewed the interesting part and this stops things from erroring so LGTM

2023-07-24 00:45 UTC, merged