Fix Item Validation
diasurgical/DevilutionX pull request #6723
Opened 2023-10-18 21:12 UTC by kphoenix137

Item validation was missing logic to consider container drops (which is problematic in Hellfire since the Crypt can drop ilvl 32 and 34 items). Also added documentation. Also we have been letting items that have the ilvl that matches the mlvl of Defiler and Na-Krul pass validation; This shouldn't happen because these monsters never drop items equal to their mlvl (Book of Apocalypse doesn't count, because the level of the book is derived from another formula, which coincedentally is 40).

2023-10-18 23:05 UTC, StephenCWills commented on Source/pack.cpp
>  		return false;
I find it unusual to put comments inside single-line if statements in C++.
```suggestion
	if (isPregenItem) {
		// Pregen flags are discarded when an item is picked up, therefore impossible to have in the inventory
		return false;
	}
```

2023-10-18 23:05 UTC, StephenCWills commented on Source/pack.cpp
>  		return false;
```suggestion
	if (isTownItem && hasMultipleFlags(iCreateInfo)) {
		// Items from town can only have 1 towner flag
		return false;
	}
```

2023-10-18 23:05 UTC, StephenCWills commented on Source/pack.cpp
> +	diabloMaxDungeonLevel -= 1;
```suggestion
	diabloMaxDungeonLevel--;
```

2023-10-18 23:06 UTC, kphoenix137 commented
Note: I have not done any thorough testing in game to make sure this operates as intended. I can this upcoming weekend, however I would like to just put that out there that this needs to be reviewed with caution to ensure it's working as intended.

2023-10-18 23:10 UTC, StephenCWills requested changes

2023-10-18 23:10 UTC, StephenCWills commented on Source/pack.cpp
>  		}
Looks like Hork Demon is in the same boat as Na-Krul and Defiler. He only drops Theodore or an amulet with ilvl 26.

https://github.com/diasurgical/devilutionX/blob/4467b8424a3d0ba7cc387b487a89de2453b20db9/Source/monster.cpp#L877-L882

2023-10-19 01:19 UTC, StephenCWills approved these changes

2023-10-19 07:34 UTC, merged

2024-02-12 23:11 UTC, Songoo7 commented
Maybe connected :?P , couldnt pick up book of apocalypse, and it sent some error packet message .
https://clips.twitch.tv/PlayfulLovelyKumquatPraiseIt-YLQZjQ_V-uz7Cuto
https://clips.twitch.tv/ThirstyWildRaccoonPJSalt-X6rrOYo0nR4q-3Cr