Fix Underministic Item Generation
diasurgical/devilutionX pull request #7058
Opened 2024-04-08 01:10 UTC by kphoenix137

Gharbad and Zhar the Mad can keep changing their rolls in Single Player by doing anything that advances the random seed, and then talking to them. Exploitable behavior using save/load game.

2024-04-08 01:38 UTC, StephenCWills requested changes
How about `DiscardRandomValues(10)` instead of `AdvanceRndSeed()`?

2024-04-11 21:35 UTC, kphoenix137 commented
> How about `DiscardRandomValues(10)` instead of `AdvanceRndSeed()`?

How do I mark this as resolved?

2024-04-11 21:38 UTC, StephenCWills approved these changes
I have a feeling this is going to conflict with my RNG changes, but the code looks good.

2024-09-15 12:45 UTC, AJenbo commented
This appears to break tests, is that expected?

2024-09-15 12:51 UTC, StephenCWills commented
No, not expected. I believe it was made at a time when the tests were broken in master. Probably just needs a rebase.

2024-09-15 13:00 UTC, AJenbo approved these changes

2024-09-15 13:12 UTC, merged