Revise Teleport Target
diasurgical/devilutionX pull request #7531
Opened 2024-11-11 18:33 UTC by kphoenix137

Currently, if the player holds right click with Teleport selected, this causes the game to select a tile as the Teleport target, and then select the same tile as the queued Teleport target, resulting in the player casting every other Teleport with no movement.

This PR does the following:

If the player is casting Teleport and the new target tile is the same as the currently targeted tile (or any nearby tile) by the currently executed Teleport spell, get the relative distance between the player and the new target tile, and add that to the currently executed tile, then Teleport the player there instead.

This allows the player to keep the mouse still and continuously queue Teleport to move in a direction. However, this does not work consistently if the player is moving the mouse around while doing this, since the player will end up zigzagging, as the queued tile can end up being different enough at this point from the executed tile. This isn't a new problem, but an existing potential annoyance due to spells targeting fixed positions rather than relative positions. The only way around that is to completely move Teleport to a relative target system, however doing so can end up being incredibly disruptive to gameplay and I don't believe it should be done.

2024-11-11 21:00 UTC, julealgon commented
@kphoenix137 after the player is teleported, are there no animation frames at all to still play?

I don't remember looking this up, but I assume actual teleportation happens on the hit-frame (around half-way through the casting animation) and then the rest of the casting animation plays on the target tile.

If that is indeed the case, you could instead only allow teleport to be queued after the hit-frame has already happened, in which case the new queued command will respect the new target tile based on the final destination + player cursor's new position.

I guess this would still potentially add that single frame of delay because of the standard animation-cancelling on hit-frame... oh well, if that's the case, disregard my suggestion.

This would work a lot more smoothly without animation cancelling 😛

2024-11-11 21:11 UTC, kphoenix137 commented
> @kphoenix137 after the player is teleported, are there no animation frames at all to still play?
> 
> I don't remember looking this up, but I assume actual teleportation happens on the hit-frame (around half-way through the casting animation) and then the rest of the casting animation plays on the target tile.
> 
> If that is indeed the case, you could instead only allow teleport to be queued after the hit-frame has already happened, in which case the new queued command will respect the new target tile based on the final destination + player cursor's new position.
> 
> I guess this would still potentially add that single frame of delay because of the standard animation-cancelling on hit-frame... oh well, if that's the case, disregard my suggestion.
> 
> This would work a lot more smoothly without animation cancelling 😛

Yes that would actually fall under what I described at the end.

2024-11-11 21:29 UTC, StephenCWills requested changes

2024-11-11 21:29 UTC, StephenCWills commented on Source/player.cpp
> +		        myPlayer.position.temp + Direction::NorthWest)) {
```suggestion
		if (cursPosition.WalkingDistance(myPlayer.position.temp) <= 1) {
```

2024-11-11 21:31 UTC, StephenCWills approved these changes

2024-11-11 21:35 UTC, qndel commented
How about moving new code to where it's actually used? Mini optimization as currently it's being calculated even when you have no mana, moving it after that early return would handle that :D

2024-11-11 21:46 UTC, StephenCWills commented
I guess you could even put it inside the `else`, since that's the only branch that uses `targetedTile`.

2024-11-12 01:26 UTC, StephenCWills approved these changes

2024-11-12 09:13 UTC, qndel approved these changes

2024-11-12 09:14 UTC, merged