Add 'E' key to stop walking and cancel pending actions
diasurgical/devilutionX pull request #952
Opened 2020-12-27 02:04 UTC by julealgon

This PR introduces a new action that the player can now perform by pressing the `E` key:
- Stops any walking after the current tile
- Cancels any queued up/buffered action, like attacking, talking, interacting with objects, etc

This allows for more fine grained control of the character without having to resort to things like attacking in-place or casting a skill to stop the current action/stop walking.

2020-12-27 07:43 UTC, qndel requested changes
I don't think any other function takes PlayerStruct as an argument so just pass player number and do plr[pnum] inside the function

2020-12-27 07:47 UTC, AJenbo commented
Hmm, would this be properly communicated in multiplayer?

2020-12-27 21:50 UTC, julealgon commented
@qndel 
> I don't think any other function takes PlayerStruct as an argument so just pass player number and do plr[pnum] inside the function

There are already functions in recent changes using C++ references. Check `spells.cpp` for a few examples. Using references like this leads to considerably cleaner code. The only reason they were not being used before is that most of the codebase is pure C and not C++.

2020-12-27 21:53 UTC, julealgon commented
@AJenbo 
> Hmm, would this be properly communicated in multiplayer?

Interesting question... I'm not 100% sure of that, but I suspect the messages are sent when the actions are executed. i.e. on each tile walk when `walkpath` is inspected, or on the final destination action when it runs. Thus, if I cancel those out early, there won't be any messages sent forward and it will effectively cancel it on MP as well. That's only an assumption though.

Do you have suggestions on how I could test this?

2020-12-27 22:39 UTC, AJenbo commented
Run two instances of the game in widescreen windowed, start and join a multiplayer game, have one player walk on a straight path across the screen where the other play can see, can press E to stop walking right at the start.

Notice if the other player sees the player stop or if it keeps walking to the original destination, or even one step further.

2020-12-27 23:34 UTC, julealgon commented
@AJenbo 
> Run two instances of the game in widescreen windowed

Nice. I didn't know you could run multiple instances of the game at once!

> ... start and join a multiplayer game...

As mentioned on discord, the instance connecting to the created game is crashing to desktop for me. If one of you could do a quick test of this it would be appreciated, otherwise I'd just have to wait it out until that is fixed as I have zero idea of what is happening there:

![image](https://user-images.githubusercontent.com/461579/103181716-d61b6500-4882-11eb-9fe6-effd9ca5d0e7.png)

2020-12-27 23:39 UTC, qndel commented
works fine for me

2021-01-02 18:06 UTC, julealgon commented
Rebased and modified slightly to reuse an existing function to clear the player's walk path.

2021-01-02 18:15 UTC, galaxyhaxz commented
> Stops any walking after the current tile

$1 million challenge: make it stop on the current pixel exactly when you press it ;)

2021-01-09 14:12 UTC, qndel approved these changes
Looks good but I can't see the difference with it and without xD must be using it wrong

2021-02-14 21:14 UTC, julealgon commented
Rebased again to remove conflict.

2021-02-18 04:40 UTC, qndel approved these changes
Looks good 👍

2021-02-27 22:10 UTC, julealgon commented
Bump @AJenbo

2021-04-04 18:15 UTC, julealgon commented
Rebased again and updated the implementation slightly.

2021-04-07 04:24 UTC, qndel commented
I'm a huge fan of this PR but personally I'd go with changing as little as possible 🤷 why the sudden rewrite? :P

2021-04-07 15:59 UTC, julealgon commented
> I'd go with changing as little as possible 🤷 why the sudden rewrite? :P

I follow the "make the change easy then make the easy change" mantra when it comes to development, so i airways try to do some refactoring work whenever i make any changes.

They should always be in separate commits, however.

Why are you against making changes @qndel ? Now that we are free from the shackles of Hellfire, we can massively improve on the codebase.

2021-04-10 04:05 UTC, julealgon commented
Rebased.

2021-04-10 22:49 UTC, julealgon commented
Rebased.

2021-04-16 02:45 UTC, julealgon commented
Rebased again.

2021-05-04 21:58 UTC, AJenbo commented
please rebase and make it integrate with the keymapper (no default key for now)

2021-05-04 22:34 UTC, julealgon commented
> please rebase and make it integrate with the keymapper (no default key for now)

Done. Also updated PR title, commit title, and removed references in help since it does not have a standard key anymore.

2021-05-04 22:38 UTC, AJenbo approved these changes

2021-05-04 22:38 UTC, merged